### ISSUE TITLE
Trouble setting push route

### ISSUE THREAD

**Issue by hath995** [sous-chefs/openvpn#103]
I've been trying to make a recipe that pushes a route just using the default configuration. However, the route doesn't show up. Do I need to the LWRP to create a server.conf that has a push route?
example default atttribute in recipe
```ruby
normal['openvpn']['push_routes'] = ['10.0.0.0 255.255.0.0']
```

**Comment by flaccid** [comment]
The provider can support either attributes from the LWRP or node attributes, https://github.com/sous-chefs/openvpn/blob/master/providers/conf.rb#L37.

**Comment by hath995** [comment]
So to clarify, the above line is not working. The push route does not appear in server.conf using the openvpn::default.

So it looks like that line defaults to the LWRP instead of using the node attribute, so I can't use the node attribute without setting up my own LWRP. Is that correct?

**Comment by devsibwarra** [comment]
There is no default value for the LWRP `push_routes` variable according to [resources/conf.rb](https://github.com/sous-chefs/openvpn/blob/master/resources/conf.rb#L25-L26), so it should evaluate to `nil` and use the value from `node['openvpn']['push_routes']`

Have you added any debugging to your Chef run to identify what `node['openvpn']` looks like when it is evaluating the config template?

**Comment by hath995** [comment]
I actually have figured it out. I am using the current version in chef super 2.1.0, which didn't have an option for push_routes, like the master version of this repo.

**Comment by flaccid** [comment]
Super!
