### ISSUE TITLE
Bad attribute call in Rakefile template

### ISSUE THREAD

**Issue by julienlevasseur** [sous-chefs/openvpn#106]
### Cookbook version
3.0.0

### Scenario:
The .conf and .ovpn files generated with rake doesn't have the openvpn port on the remote line.

### Expected Result:
remote #{gateway} #{port}

### Actual Result:
remote #{gateway}

### Proposition:

See : https://github.com/julienlevasseur/openvpn/commit/752725366df6ffdb4db9465e36155baad21a3c6e

**Comment by flaccid** [comment]
@julienlevasseur LGTM, quick PR and we'll merge please.
