### ISSUE TITLE
recipies mentioned in readme missing in package.

### ISSUE THREAD

**Issue by naviens** [sous-chefs/openvpn#108]
### Cookbook version
2.1.0, 2.0.4

### Chef-client version
12
### Platform Details
ubuntu 16.04
### Scenario:
some recipies were missing in package mentioned in readme (openvpn::server)

### Steps to Reproduce:
run recipie openvpn::server

### Expected Result:
to initiate openvpn::server

### Actual Result:
Chef::Exceptions::RecipeNotFound
--------------------------------
could not find recipe server for cookbook openvpn

**Comment by flaccid** [comment]
This recipe is not mentioned in either of the mentioned versions:
https://github.com/sous-chefs/openvpn/blob/534191af5453978b4d6b7be22a8de454699525cb/README.md#recipes
https://github.com/sous-chefs/openvpn/blob/b826c0ae8615699767f5d1773f7f74f18688e7ea/README.md#recipes

Only the `default` and `users` recipes are referred to in the readme for each of these versions. Perhaps you are looking at the master branch for the readme.

**Comment by nkblue** [comment]
I am seeing the same issue with 2.1.0.

I have a role:
```
name "openvpn"
description "openvpn role for topaz cluster"

run_list [
  'recipe[openvpn::server]'
]
```

metadata.rb:
```
depends          'openvpn'
```

and I am getting the error: `could not find recipe server for cookbook openvpn`

If I change it to `'recipe[openvpn::default]'` it runs fine. None of the other recipes seem to work.

**Comment by flaccid** [comment]
@nkblue Please read my previous comment, https://github.com/sous-chefs/openvpn/issues/108#issuecomment-301350534. v2.1.0 did not have a server recipe which is clear in the readme from that tag: https://github.com/sous-chefs/openvpn/tree/v2.1.0#recipes. Please don't look at the readme in current master for historic versions :)

**Comment by nkblue** [comment]
@flaccid I sorted it out but I think the README could be a bit more clear.
For me the issue was that in my Berksfile I had only `cookbook 'openvpn'` which I assumed would pull the latest version, but it only gave me a `2.0.*` release.

Then I assumed the latest was `2.1.0` based on this: https://supermarket.chef.io/cookbooks/openvpn

Without a definitive `cookbook 'openvpn', git: 'https://github.com/sous-chefs/openvpn'` in the README its slightly confusing.

**Comment by flaccid** [comment]
The reason for this is that v3 is not yet released which is what is currently in master, 8 more issues to complete https://github.com/sous-chefs/openvpn/milestones. Assistance appreciated.

**Comment by nkblue** [comment]
@flaccid Thanks for your efforts. Much appreciated.
