### ISSUE TITLE
Args option

### ISSUE THREAD

**Issue by obazoud** [sous-chefs/openvpn#111]
### Cookbook version
[Version of the cookbook where you are encountering the issue]

### Chef-client version
[Version of chef-client in your environment]

### Platform Details
[Operating system distribution and release version. Cloud provider if running in the cloud]

### Scenario:

I would like to add to openvpn args " --status-version 2" to use with collectd plugin (https://collectd.org/documentation/manpages/collectd.conf.5.shtml#plugin_openvpn).

By default, status version is 1

```
       --status-version [n]
              Choose the status file format version number.  Currently n can be 1, 2, or 3 and defaults to 1.
```

I don't see how to do that in this cookbook. Any idea ?

### Steps to Reproduce:
[If you are filing an issue what are the things we need to do in order to repro your problem? How are you using this cookbook or any resources it includes?]

### Expected Result:
[What are you expecting to happen as the consequence of above reproduction steps?]

### Actual Result:
[What actually happens after the reproduction steps? Include the error output or a link to a gist if possible.]

**Comment by devsibwarra** [comment]
@obazoud There are 2 ways to do this, though if you only have 1 openvpn instance the global setting would be easiest.

## Method 1: global setting
Set `node['openvpn']['config']['status-version'] = 2` in your environment, role, or node config.  This will cause all openvpn instances to receive this setting

## Method 2: per-instance
In your wrapper cookbook, add `['status-version'] = 2` to a hash that is passed to the `openvpn_conf` resource via the `config` parameter

```
  myvpnconfig = {
    ... additional instance specific vpn settings ...,
    'status-version' => 2
  }
  openvpn_conf 'test' do
    config node['openvpn']['config'].merge(myvpnconfig)
  end
```

**Comment by obazoud** [comment]
Thanks!! I will give a try
