### ISSUE TITLE
Cookbook Updated But Not Showing in Supermarket

### ISSUE THREAD

**Issue by kylegoch** [sous-chefs/openvpn#114]
Glad to see this cookbook adopted and bumped to version 3.0.0 but the supermarket is still showing 2.1.0 as the latest.

**Comment by tas50** [comment]
The metadata version has been bumped, but the cookbook has not yet been released. In the future we'll avoid dumping the version until we actually do a release since it's a big confusing

**Comment by flaccid** [comment]
https://github.com/sous-chefs/openvpn/milestone/1

**Comment by damacus** [comment]
Hi @kylegoch we've released v3 of the cookbokok to ship the current set of fixes. I would recommend a higher than normal case of wary-ness as this is a major cookbook version bump
