### ISSUE TITLE
Questions about openssl.cnf template management

### ISSUE THREAD

**Issue by dragonsmith** [sous-chefs/openvpn#128]
Hello,
I'm not posting a real issue with that, but want to ask for your help and comments regarding `openssl.cnf` file management in this cookbook.

1. I see this cookbook creates `openssl.cnf` twice. [Here](https://github.com/sous-chefs/openvpn/blob/master/recipes/server.rb#L49-L56), for easy-rsa dir, and [here](https://github.com/sous-chefs/openvpn/blob/master/recipes/server.rb#L72-L77), for keys dir. What is the idea behind that? Why cannot we use just one file, especially if they are the same?
2. I see attribute `message_digest` [here](https://github.com/sous-chefs/openvpn/blob/master/attributes/default.rb#L45). I'm thinking if we can apply it to `openssl.cnf` to the `default_md` [option](https://github.com/sous-chefs/openvpn/blob/master/templates/openssl.cnf.erb#L25). easy-rsa will use it to issue client certificates and renewing the CRL file. What do you think?
3. The default validity time for CRL file is [30 days](https://github.com/sous-chefs/openvpn/blob/master/templates/openssl.cnf.erb#L24) Is it wise to suggest making it configurable too?

Of course, I'm willing to provide a PR for all these moments if you see them as reasonable suggestions.

Thank you in advance for your time!

**Comment by stefanor** [comment]
> The default validity time for CRL file is 30 days Is it wise to suggest making it configurable too?

That is achieved in #129.

**Comment by damacus** [comment]
CLosed via #129
