### ISSUE TITLE
Should we add the official openvpn apt repository on Debian/Ubuntu

### ISSUE THREAD

**Issue by maf23** [sous-chefs/openvpn#131]
Currently this cookbook only installs the stock openvpn. This version often lags so OpenVPN has their own official apt repository.

I propose that we change this cookbook to automatically add that repository on Debian/Ubuntu systems. I can probably take a stab at implementing this if the maintainer thinks it is a good idea.

**Comment by damacus** [comment]
Yup! That's actually our on-official preference, reference anything we've properly rewritten in the last year. 

Generally I/we tend to stop using ubuntu/centos repos over a vendor provided one because of patches.

**Comment by maf23** [comment]
I'll take a stab at it then.

**Comment by Xorima** [comment]
Hi @maf23 

Do you know if this can be closed?

Thanks!

**Comment by maf23** [comment]
Yes, it can be closed.
