### ISSUE TITLE
Interest in handling user removal & suspension?

### ISSUE THREAD

**Issue by toddmichael** [sous-chefs/openvpn#55]
Looking through the code/doc, I don't see a solution for:
- removing credentials for users with "remove" action
- suspending credentials for users with "lock" action

Let me know if I just missed it or if folks are handling in a different manner.  If not, is there any interest in supporting either of these use cases?  If so, I can do my work in this cookbook and submit as PR.  Otherwise, will just handle via wrapper.  

Cheers,

Todd

**Comment by flaccid** [comment]
Yes please. This would be a most welcomed contribution. A rake task for it would be good too.

**Comment by eherot** [comment]
Yes, please. I added #48 to facilitate this so having it be fully supported would be very helpful indeed.

**Comment by flaccid** [comment]
@toddmichael @eherot any chance of a pull request to the readme on how to do the user story of this issue? i.e.

how to:
- remove credentials for users with "remove" action
- suspend credentials for users with "lock" action

If we are still missing functionality in master, lets fix that up. Have added this to milestone v3.

**Comment by flaccid** [comment]
Relates to https://github.com/xhost-cookbooks/openvpn/pull/82.

**Comment by georgiou** [comment]
https://github.com/xhost-cookbooks/openvpn/pull/99

**Comment by damacus** [comment]
Closed via #99
